### ISSUE TITLE
Help - creating story

### ISSUE THREAD

**Issue by evaneus** [andjosh/clubhouse-cli#47]
After installing and verifying that find command works, tried the following command:

`club create -t 'story title' -E 646 -p 86 -l "my label" -d "my description"`

(also tried with `"` quotes on number fields and string fields, and with `--title` and `--project` options. Verified epic and project ids exist.)

### Expected Behavior

Should create a story.

### Actual Behavior

returns:

`Must provide --title and --project`

### Steps to Reproduce

see above.

**Comment by andjosh** [comment]
Hi @evaneus! Thanks for the bug report.

So, that message would appear if `club` can't find the project you're supplying (Project `89`, in this case). It failed because Clubhouse requires each story to belong to a Project.

When you run `club projects`, do you see a Project with an ID or name with `89`?

**Comment by evaneus** [comment]
whoops, I could have sworn I double checked those ids 😊
Sorry for the erroneous report.

**Comment by cem2ran** [comment]
I've been unable to use this tool to create stories as I'm getting the above reported error even though I have supplied a valid title and project id. I was able to find a version that still works (1.14.0).

I was able to find a commit which may have introduced the regression: https://github.com/andjosh/clubhouse-cli/commit/2b02329c5b9ca03e594b4fa02c57cc698f7c1a6e

Commit prior to above still works. @andjosh maybe you have a better idea about what broke?

**Comment by andjosh** [comment]
@cem2ran Thank you so much for pointing that out!
It seems there was a simply copy pasta issue (fixed in https://github.com/andjosh/clubhouse-cli/commit/0b12d25edd621957ceb18da893d660216ee78880 and released in https://github.com/andjosh/clubhouse-cli/releases/tag/v2.0.3). Do you also need the fix released in v1.14.x or are you good to go up to version 2.0.x now?

**Comment by cem2ran** [comment]
@andjosh I'd be happy to use the latest version :)
